/*
 * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 *
 */

// Code generated by informer-gen. DO NOT EDIT.

package v2

import (
	"context"
	time "time"

	ccebaidubcecomv2 "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/apis/cce.baidubce.com/v2"
	versioned "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v2 "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/client/listers/cce.baidubce.com/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodSubnetTopologySpreadInformer provides access to a shared informer and lister for
// PodSubnetTopologySpreads.
type PodSubnetTopologySpreadInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v2.PodSubnetTopologySpreadLister
}

type podSubnetTopologySpreadInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodSubnetTopologySpreadInformer constructs a new informer for PodSubnetTopologySpread type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodSubnetTopologySpreadInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodSubnetTopologySpreadInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodSubnetTopologySpreadInformer constructs a new informer for PodSubnetTopologySpread type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodSubnetTopologySpreadInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				options.AllowWatchBookmarks = true
				return client.CceV2().PodSubnetTopologySpreads(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				options.AllowWatchBookmarks = true
				return client.CceV2().PodSubnetTopologySpreads(namespace).Watch(context.TODO(), options)
			},
		},
		&ccebaidubcecomv2.PodSubnetTopologySpread{},
		resyncPeriod,
		indexers,
	)
}

func (f *podSubnetTopologySpreadInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodSubnetTopologySpreadInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podSubnetTopologySpreadInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ccebaidubcecomv2.PodSubnetTopologySpread{}, f.defaultInformer)
}

func (f *podSubnetTopologySpreadInformer) Lister() v2.PodSubnetTopologySpreadLister {
	return v2.NewPodSubnetTopologySpreadLister(f.Informer().GetIndexer())
}
