// Code generated by go-swagger; DO NOT EDIT.

// /*
//  * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  * except in compliance with the License. You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software distributed under the
//  * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
//  * either express or implied. See the License for the specific language governing permissions
//  * and limitations under the License.
//  *
//  */

package eni

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteEniHandlerFunc turns a function with the right signature into a delete eni handler
type DeleteEniHandlerFunc func(DeleteEniParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteEniHandlerFunc) Handle(params DeleteEniParams) middleware.Responder {
	return fn(params)
}

// DeleteEniHandler interface for that can handle valid delete eni params
type DeleteEniHandler interface {
	Handle(DeleteEniParams) middleware.Responder
}

// NewDeleteEni creates a new http.Handler for the delete eni operation
func NewDeleteEni(ctx *middleware.Context, handler DeleteEniHandler) *DeleteEni {
	return &DeleteEni{Context: ctx, Handler: handler}
}

/*
DeleteEni swagger:route DELETE /eni eni deleteEni

Release an allocated IP address for exclusive ENI
*/
type DeleteEni struct {
	Context *middleware.Context
	Handler DeleteEniHandler
}

func (o *DeleteEni) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteEniParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
