// Code generated by go-swagger; DO NOT EDIT.

// /*
//  * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  * except in compliance with the License. You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software distributed under the
//  * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
//  * either express or implied. See the License for the specific language governing permissions
//  * and limitations under the License.
//  *
//  */

package eni

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostEniHandlerFunc turns a function with the right signature into a post eni handler
type PostEniHandlerFunc func(PostEniParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostEniHandlerFunc) Handle(params PostEniParams) middleware.Responder {
	return fn(params)
}

// PostEniHandler interface for that can handle valid post eni params
type PostEniHandler interface {
	Handle(PostEniParams) middleware.Responder
}

// NewPostEni creates a new http.Handler for the post eni operation
func NewPostEni(ctx *middleware.Context, handler PostEniHandler) *PostEni {
	return &PostEni{Context: ctx, Handler: handler}
}

/*
PostEni swagger:route POST /eni eni postEni

Allocate an IP address for exclusive ENI
*/
type PostEni struct {
	Context *middleware.Context
	Handler PostEniHandler
}

func (o *PostEni) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostEniParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
