//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 *
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v2alpha1

import (
	v2 "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/apis/cce.baidubce.com/v2"
	model "github.com/baidubce/bce-sdk-go/model"
	api "github.com/baidubce/bce-sdk-go/services/bcc/api"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfig) DeepCopyInto(out *AgentConfig) {
	*out = *in
	if in.EniSubnetIDs != nil {
		in, out := &in.EniSubnetIDs, &out.EniSubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableRDMA != nil {
		in, out := &in.EnableRDMA, &out.EnableRDMA
		*out = new(bool)
		**out = **in
	}
	if in.ManualMTU != nil {
		in, out := &in.ManualMTU, &out.ManualMTU
		*out = new(int)
		**out = **in
	}
	if in.EniUseMode != nil {
		in, out := &in.EniUseMode, &out.EniUseMode
		*out = new(string)
		**out = **in
	}
	if in.EniSecurityGroupIds != nil {
		in, out := &in.EniSecurityGroupIds, &out.EniSecurityGroupIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EniEnterpriseSecurityGroupIds != nil {
		in, out := &in.EniEnterpriseSecurityGroupIds, &out.EniEnterpriseSecurityGroupIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BurstableMehrfachENI != nil {
		in, out := &in.BurstableMehrfachENI, &out.BurstableMehrfachENI
		*out = new(int)
		**out = **in
	}
	if in.ReleaseExcessIPs != nil {
		in, out := &in.ReleaseExcessIPs, &out.ReleaseExcessIPs
		*out = new(bool)
		**out = **in
	}
	if in.ExtCniPlugins != nil {
		in, out := &in.ExtCniPlugins, &out.ExtCniPlugins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UsePrimaryAddress != nil {
		in, out := &in.UsePrimaryAddress, &out.UsePrimaryAddress
		*out = new(bool)
		**out = **in
	}
	if in.IPPoolPreAllocateENI != nil {
		in, out := &in.IPPoolPreAllocateENI, &out.IPPoolPreAllocateENI
		*out = new(int)
		**out = **in
	}
	if in.IPPoolMinAllocate != nil {
		in, out := &in.IPPoolMinAllocate, &out.IPPoolMinAllocate
		*out = new(int)
		**out = **in
	}
	if in.IPPoolPreAllocate != nil {
		in, out := &in.IPPoolPreAllocate, &out.IPPoolPreAllocate
		*out = new(int)
		**out = **in
	}
	if in.IPPoolMaxAboveWatermark != nil {
		in, out := &in.IPPoolMaxAboveWatermark, &out.IPPoolMaxAboveWatermark
		*out = new(int)
		**out = **in
	}
	if in.RouteTableOffset != nil {
		in, out := &in.RouteTableOffset, &out.RouteTableOffset
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfig.
func (in *AgentConfig) DeepCopy() *AgentConfig {
	if in == nil {
		return nil
	}
	out := new(AgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodSubnetTopologySpread) DeepCopyInto(out *ClusterPodSubnetTopologySpread) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodSubnetTopologySpread.
func (in *ClusterPodSubnetTopologySpread) DeepCopy() *ClusterPodSubnetTopologySpread {
	if in == nil {
		return nil
	}
	out := new(ClusterPodSubnetTopologySpread)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPodSubnetTopologySpread) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodSubnetTopologySpreadList) DeepCopyInto(out *ClusterPodSubnetTopologySpreadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPodSubnetTopologySpread, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodSubnetTopologySpreadList.
func (in *ClusterPodSubnetTopologySpreadList) DeepCopy() *ClusterPodSubnetTopologySpreadList {
	if in == nil {
		return nil
	}
	out := new(ClusterPodSubnetTopologySpreadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPodSubnetTopologySpreadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodSubnetTopologySpreadSpec) DeepCopyInto(out *ClusterPodSubnetTopologySpreadSpec) {
	*out = *in
	in.PodSubnetTopologySpreadSpec.DeepCopyInto(&out.PodSubnetTopologySpreadSpec)
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodSubnetTopologySpreadSpec.
func (in *ClusterPodSubnetTopologySpreadSpec) DeepCopy() *ClusterPodSubnetTopologySpreadSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPodSubnetTopologySpreadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodSubnetTopologySpreadStatus) DeepCopyInto(out *ClusterPodSubnetTopologySpreadStatus) {
	*out = *in
	if in.SubStatus != nil {
		in, out := &in.SubStatus, &out.SubStatus
		*out = make(map[string]v2.PodSubnetTopologySpreadStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodSubnetTopologySpreadStatus.
func (in *ClusterPodSubnetTopologySpreadStatus) DeepCopy() *ClusterPodSubnetTopologySpreadStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPodSubnetTopologySpreadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetResourceConfigSet) DeepCopyInto(out *NetResourceConfigSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetResourceConfigSet.
func (in *NetResourceConfigSet) DeepCopy() *NetResourceConfigSet {
	if in == nil {
		return nil
	}
	out := new(NetResourceConfigSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetResourceConfigSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetResourceConfigSetList) DeepCopyInto(out *NetResourceConfigSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetResourceConfigSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetResourceConfigSetList.
func (in *NetResourceConfigSetList) DeepCopy() *NetResourceConfigSetList {
	if in == nil {
		return nil
	}
	out := new(NetResourceConfigSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetResourceConfigSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetResourceConfigSetSpec) DeepCopyInto(out *NetResourceConfigSetSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.AgentConfig.DeepCopyInto(&out.AgentConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetResourceConfigSetSpec.
func (in *NetResourceConfigSetSpec) DeepCopy() *NetResourceConfigSetSpec {
	if in == nil {
		return nil
	}
	out := new(NetResourceConfigSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetResourceConfigSetStatus) DeepCopyInto(out *NetResourceConfigSetStatus) {
	*out = *in
	if in.AgentVersion != nil {
		in, out := &in.AgentVersion, &out.AgentVersion
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetResourceConfigSetStatus.
func (in *NetResourceConfigSetStatus) DeepCopy() *NetResourceConfigSetStatus {
	if in == nil {
		return nil
	}
	out := new(NetResourceConfigSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroup) DeepCopyInto(out *SecurityGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroup.
func (in *SecurityGroup) DeepCopy() *SecurityGroup {
	if in == nil {
		return nil
	}
	out := new(SecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupList) DeepCopyInto(out *SecurityGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupList.
func (in *SecurityGroupList) DeepCopy() *SecurityGroupList {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupRules) DeepCopyInto(out *SecurityGroupRules) {
	*out = *in
	if in.Allows != nil {
		in, out := &in.Allows, &out.Allows
		*out = make([]*api.SecurityGroupRuleModel, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(api.SecurityGroupRuleModel)
				**out = **in
			}
		}
	}
	if in.Drops != nil {
		in, out := &in.Drops, &out.Drops
		*out = make([]*api.SecurityGroupRuleModel, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(api.SecurityGroupRuleModel)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupRules.
func (in *SecurityGroupRules) DeepCopy() *SecurityGroupRules {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupSpec) DeepCopyInto(out *SecurityGroupSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]model.TagModel, len(*in))
		copy(*out, *in)
	}
	in.IngressRule.DeepCopyInto(&out.IngressRule)
	in.EgressRule.DeepCopyInto(&out.EgressRule)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupSpec.
func (in *SecurityGroupSpec) DeepCopy() *SecurityGroupSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupStatus) DeepCopyInto(out *SecurityGroupStatus) {
	*out = *in
	if in.LastAlterTime != nil {
		in, out := &in.LastAlterTime, &out.LastAlterTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupStatus.
func (in *SecurityGroupStatus) DeepCopy() *SecurityGroupStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in SecurityReleation) DeepCopyInto(out *SecurityReleation) {
	{
		in := &in
		*out = make(SecurityReleation, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityReleation.
func (in SecurityReleation) DeepCopy() SecurityReleation {
	if in == nil {
		return nil
	}
	out := new(SecurityReleation)
	in.DeepCopyInto(out)
	return *out
}
