/*
 * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 *
 */

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	"context"
	"time"

	v2 "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/apis/cce.baidubce.com/v2"
	scheme "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ENIsGetter has a method to return a ENIInterface.
// A group's client should implement this interface.
type ENIsGetter interface {
	ENIs() ENIInterface
}

// ENIInterface has methods to work with ENI resources.
type ENIInterface interface {
	Create(ctx context.Context, eNI *v2.ENI, opts v1.CreateOptions) (*v2.ENI, error)
	Update(ctx context.Context, eNI *v2.ENI, opts v1.UpdateOptions) (*v2.ENI, error)
	UpdateStatus(ctx context.Context, eNI *v2.ENI, opts v1.UpdateOptions) (*v2.ENI, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2.ENI, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2.ENIList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.ENI, err error)
	ENIExpansion
}

// eNIs implements ENIInterface
type eNIs struct {
	client rest.Interface
}

// newENIs returns a ENIs
func newENIs(c *CceV2Client) *eNIs {
	return &eNIs{
		client: c.RESTClient(),
	}
}

// Get takes name of the eNI, and returns the corresponding eNI object, and an error if there is any.
func (c *eNIs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.ENI, err error) {
	result = &v2.ENI{}
	err = c.client.Get().
		Resource("enis").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ENIs that match those selectors.
func (c *eNIs) List(ctx context.Context, opts v1.ListOptions) (result *v2.ENIList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2.ENIList{}
	err = c.client.Get().
		Resource("enis").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested eNIs.
func (c *eNIs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("enis").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a eNI and creates it.  Returns the server's representation of the eNI, and an error, if there is any.
func (c *eNIs) Create(ctx context.Context, eNI *v2.ENI, opts v1.CreateOptions) (result *v2.ENI, err error) {
	result = &v2.ENI{}
	err = c.client.Post().
		Resource("enis").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(eNI).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a eNI and updates it. Returns the server's representation of the eNI, and an error, if there is any.
func (c *eNIs) Update(ctx context.Context, eNI *v2.ENI, opts v1.UpdateOptions) (result *v2.ENI, err error) {
	result = &v2.ENI{}
	err = c.client.Put().
		Resource("enis").
		Name(eNI.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(eNI).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *eNIs) UpdateStatus(ctx context.Context, eNI *v2.ENI, opts v1.UpdateOptions) (result *v2.ENI, err error) {
	result = &v2.ENI{}
	err = c.client.Put().
		Resource("enis").
		Name(eNI.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(eNI).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the eNI and deletes it. Returns an error if one occurs.
func (c *eNIs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("enis").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *eNIs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("enis").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched eNI.
func (c *eNIs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.ENI, err error) {
	result = &v2.ENI{}
	err = c.client.Patch(pt).
		Resource("enis").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
