operator:
  manager:
    args:
    - --region={{ .Region }}
    - --cce-cluster-id={{ .ClusterID }}
    env:
      cceGatewayEndpoint: {{ .CCEGatewayEndpoint }}
    image:
      repository: {{ .ImageRepository }}
      tag: {{ .ImageTag }}
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
  replicas: 1
