// Code generated by go-swagger; DO NOT EDIT.

// /*
//  * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  * except in compliance with the License. You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software distributed under the
//  * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
//  * either express or implied. See the License for the specific language governing permissions
//  * and limitations under the License.
//  *
//  */

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddressPair Addressing information of an endpoint
//
// swagger:model AddressPair
type AddressPair struct {

	// IPv4 address
	IPV4 string `json:"ipv4,omitempty"`

	// UUID of IPv4 expiration timer
	IPV4ExpirationUUID string `json:"ipv4-expiration-uuid,omitempty"`

	// IPv6 address
	IPV6 string `json:"ipv6,omitempty"`

	// UUID of IPv6 expiration timer
	IPV6ExpirationUUID string `json:"ipv6-expiration-uuid,omitempty"`
}

// Validate validates this address pair
func (m *AddressPair) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressPair) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressPair) UnmarshalBinary(b []byte) error {
	var res AddressPair
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
