// Code generated by go-swagger; DO NOT EDIT.

// /*
//  * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  * except in compliance with the License. You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software distributed under the
//  * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
//  * either express or implied. See the License for the specific language governing permissions
//  * and limitations under the License.
//  *
//  */

package rdmaipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/api/v1/models"
)

// DeleteRdmaipamRdmaipsReader is a Reader for the DeleteRdmaipamRdmaips structure.
type DeleteRdmaipamRdmaipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRdmaipamRdmaipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRdmaipamRdmaipsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRdmaipamRdmaipsInvalid()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteRdmaipamRdmaipsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRdmaipamRdmaipsFailure()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewDeleteRdmaipamRdmaipsDisabled()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRdmaipamRdmaipsOK creates a DeleteRdmaipamRdmaipsOK with default headers values
func NewDeleteRdmaipamRdmaipsOK() *DeleteRdmaipamRdmaipsOK {
	return &DeleteRdmaipamRdmaipsOK{}
}

/*
DeleteRdmaipamRdmaipsOK handles this case with default header values.

Success
*/
type DeleteRdmaipamRdmaipsOK struct {
}

func (o *DeleteRdmaipamRdmaipsOK) Error() string {
	return fmt.Sprintf("[DELETE /rdmaipam/{rdmaips}][%d] deleteRdmaipamRdmaipsOK ", 200)
}

func (o *DeleteRdmaipamRdmaipsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRdmaipamRdmaipsInvalid creates a DeleteRdmaipamRdmaipsInvalid with default headers values
func NewDeleteRdmaipamRdmaipsInvalid() *DeleteRdmaipamRdmaipsInvalid {
	return &DeleteRdmaipamRdmaipsInvalid{}
}

/*
DeleteRdmaipamRdmaipsInvalid handles this case with default header values.

Invalid IP address
*/
type DeleteRdmaipamRdmaipsInvalid struct {
}

func (o *DeleteRdmaipamRdmaipsInvalid) Error() string {
	return fmt.Sprintf("[DELETE /rdmaipam/{rdmaips}][%d] deleteRdmaipamRdmaipsInvalid ", 400)
}

func (o *DeleteRdmaipamRdmaipsInvalid) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRdmaipamRdmaipsNotFound creates a DeleteRdmaipamRdmaipsNotFound with default headers values
func NewDeleteRdmaipamRdmaipsNotFound() *DeleteRdmaipamRdmaipsNotFound {
	return &DeleteRdmaipamRdmaipsNotFound{}
}

/*
DeleteRdmaipamRdmaipsNotFound handles this case with default header values.

IP address not found
*/
type DeleteRdmaipamRdmaipsNotFound struct {
}

func (o *DeleteRdmaipamRdmaipsNotFound) Error() string {
	return fmt.Sprintf("[DELETE /rdmaipam/{rdmaips}][%d] deleteRdmaipamRdmaipsNotFound ", 404)
}

func (o *DeleteRdmaipamRdmaipsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRdmaipamRdmaipsFailure creates a DeleteRdmaipamRdmaipsFailure with default headers values
func NewDeleteRdmaipamRdmaipsFailure() *DeleteRdmaipamRdmaipsFailure {
	return &DeleteRdmaipamRdmaipsFailure{}
}

/*
DeleteRdmaipamRdmaipsFailure handles this case with default header values.

Address release failure
*/
type DeleteRdmaipamRdmaipsFailure struct {
	Payload models.Error
}

func (o *DeleteRdmaipamRdmaipsFailure) Error() string {
	return fmt.Sprintf("[DELETE /rdmaipam/{rdmaips}][%d] deleteRdmaipamRdmaipsFailure  %+v", 500, o.Payload)
}

func (o *DeleteRdmaipamRdmaipsFailure) GetPayload() models.Error {
	return o.Payload
}

func (o *DeleteRdmaipamRdmaipsFailure) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRdmaipamRdmaipsDisabled creates a DeleteRdmaipamRdmaipsDisabled with default headers values
func NewDeleteRdmaipamRdmaipsDisabled() *DeleteRdmaipamRdmaipsDisabled {
	return &DeleteRdmaipamRdmaipsDisabled{}
}

/*
DeleteRdmaipamRdmaipsDisabled handles this case with default header values.

Allocation for address family disabled
*/
type DeleteRdmaipamRdmaipsDisabled struct {
}

func (o *DeleteRdmaipamRdmaipsDisabled) Error() string {
	return fmt.Sprintf("[DELETE /rdmaipam/{rdmaips}][%d] deleteRdmaipamRdmaipsDisabled ", 501)
}

func (o *DeleteRdmaipamRdmaipsDisabled) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
