// Code generated by go-swagger; DO NOT EDIT.

// /*
//  * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  * except in compliance with the License. You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software distributed under the
//  * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
//  * either express or implied. See the License for the specific language governing permissions
//  * and limitations under the License.
//  *
//  */

package rdmaipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostRdmaipamParams creates a new PostRdmaipamParams object
// with the default values initialized.
func NewPostRdmaipamParams() *PostRdmaipamParams {
	var ()
	return &PostRdmaipamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRdmaipamParamsWithTimeout creates a new PostRdmaipamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRdmaipamParamsWithTimeout(timeout time.Duration) *PostRdmaipamParams {
	var ()
	return &PostRdmaipamParams{

		timeout: timeout,
	}
}

// NewPostRdmaipamParamsWithContext creates a new PostRdmaipamParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRdmaipamParamsWithContext(ctx context.Context) *PostRdmaipamParams {
	var ()
	return &PostRdmaipamParams{

		Context: ctx,
	}
}

// NewPostRdmaipamParamsWithHTTPClient creates a new PostRdmaipamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRdmaipamParamsWithHTTPClient(client *http.Client) *PostRdmaipamParams {
	var ()
	return &PostRdmaipamParams{
		HTTPClient: client,
	}
}

/*
PostRdmaipamParams contains all the parameters to send to the API endpoint
for the post rdmaipam operation typically these are written to a http.Request
*/
type PostRdmaipamParams struct {

	/*ContainerID
	  container id provider by cni

	*/
	ContainerID *string
	/*Expiration*/
	Expiration *bool
	/*Family*/
	Family *string
	/*Netns
	  netns provider by cni

	*/
	Netns *string
	/*Owner*/
	Owner *string
	/*RdmaIfnames
	  rdma ifnames provider by cni

	*/
	RdmaIfnames *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post rdmaipam params
func (o *PostRdmaipamParams) WithTimeout(timeout time.Duration) *PostRdmaipamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post rdmaipam params
func (o *PostRdmaipamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post rdmaipam params
func (o *PostRdmaipamParams) WithContext(ctx context.Context) *PostRdmaipamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post rdmaipam params
func (o *PostRdmaipamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post rdmaipam params
func (o *PostRdmaipamParams) WithHTTPClient(client *http.Client) *PostRdmaipamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post rdmaipam params
func (o *PostRdmaipamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContainerID adds the containerID to the post rdmaipam params
func (o *PostRdmaipamParams) WithContainerID(containerID *string) *PostRdmaipamParams {
	o.SetContainerID(containerID)
	return o
}

// SetContainerID adds the containerId to the post rdmaipam params
func (o *PostRdmaipamParams) SetContainerID(containerID *string) {
	o.ContainerID = containerID
}

// WithExpiration adds the expiration to the post rdmaipam params
func (o *PostRdmaipamParams) WithExpiration(expiration *bool) *PostRdmaipamParams {
	o.SetExpiration(expiration)
	return o
}

// SetExpiration adds the expiration to the post rdmaipam params
func (o *PostRdmaipamParams) SetExpiration(expiration *bool) {
	o.Expiration = expiration
}

// WithFamily adds the family to the post rdmaipam params
func (o *PostRdmaipamParams) WithFamily(family *string) *PostRdmaipamParams {
	o.SetFamily(family)
	return o
}

// SetFamily adds the family to the post rdmaipam params
func (o *PostRdmaipamParams) SetFamily(family *string) {
	o.Family = family
}

// WithNetns adds the netns to the post rdmaipam params
func (o *PostRdmaipamParams) WithNetns(netns *string) *PostRdmaipamParams {
	o.SetNetns(netns)
	return o
}

// SetNetns adds the netns to the post rdmaipam params
func (o *PostRdmaipamParams) SetNetns(netns *string) {
	o.Netns = netns
}

// WithOwner adds the owner to the post rdmaipam params
func (o *PostRdmaipamParams) WithOwner(owner *string) *PostRdmaipamParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the post rdmaipam params
func (o *PostRdmaipamParams) SetOwner(owner *string) {
	o.Owner = owner
}

// WithRdmaIfnames adds the rdmaIfnames to the post rdmaipam params
func (o *PostRdmaipamParams) WithRdmaIfnames(rdmaIfnames *string) *PostRdmaipamParams {
	o.SetRdmaIfnames(rdmaIfnames)
	return o
}

// SetRdmaIfnames adds the rdmaIfnames to the post rdmaipam params
func (o *PostRdmaipamParams) SetRdmaIfnames(rdmaIfnames *string) {
	o.RdmaIfnames = rdmaIfnames
}

// WriteToRequest writes these params to a swagger request
func (o *PostRdmaipamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContainerID != nil {

		// query param containerID
		var qrContainerID string
		if o.ContainerID != nil {
			qrContainerID = *o.ContainerID
		}
		qContainerID := qrContainerID
		if qContainerID != "" {
			if err := r.SetQueryParam("containerID", qContainerID); err != nil {
				return err
			}
		}

	}

	if o.Expiration != nil {

		// header param expiration
		if err := r.SetHeaderParam("expiration", swag.FormatBool(*o.Expiration)); err != nil {
			return err
		}

	}

	if o.Family != nil {

		// query param family
		var qrFamily string
		if o.Family != nil {
			qrFamily = *o.Family
		}
		qFamily := qrFamily
		if qFamily != "" {
			if err := r.SetQueryParam("family", qFamily); err != nil {
				return err
			}
		}

	}

	if o.Netns != nil {

		// query param netns
		var qrNetns string
		if o.Netns != nil {
			qrNetns = *o.Netns
		}
		qNetns := qrNetns
		if qNetns != "" {
			if err := r.SetQueryParam("netns", qNetns); err != nil {
				return err
			}
		}

	}

	if o.Owner != nil {

		// query param owner
		var qrOwner string
		if o.Owner != nil {
			qrOwner = *o.Owner
		}
		qOwner := qrOwner
		if qOwner != "" {
			if err := r.SetQueryParam("owner", qOwner); err != nil {
				return err
			}
		}

	}

	if o.RdmaIfnames != nil {

		// query param rdmaIfnames
		var qrRdmaIfnames string
		if o.RdmaIfnames != nil {
			qrRdmaIfnames = *o.RdmaIfnames
		}
		qRdmaIfnames := qrRdmaIfnames
		if qRdmaIfnames != "" {
			if err := r.SetQueryParam("rdmaIfnames", qRdmaIfnames); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
