{{- if .Values.network.operator.webhook.enable }}
apiVersion: v1
kind: Service
metadata:
  name: cce-network-v2
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: http
  selector:
    app.cce.baidubce.com: cce-network-operator
    {{- include "helm.selectorLabels" . | nindent 4 }}
{{- end }}