/*
 * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 *
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/client/clientset/versioned/typed/cce.baidubce.com/v2alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCceV2alpha1 struct {
	*testing.Fake
}

func (c *FakeCceV2alpha1) ClusterPodSubnetTopologySpreads() v2alpha1.ClusterPodSubnetTopologySpreadInterface {
	return &FakeClusterPodSubnetTopologySpreads{c}
}

func (c *FakeCceV2alpha1) NetResourceConfigSets() v2alpha1.NetResourceConfigSetInterface {
	return &FakeNetResourceConfigSets{c}
}

func (c *FakeCceV2alpha1) SecurityGroups() v2alpha1.SecurityGroupInterface {
	return &FakeSecurityGroups{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCceV2alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
