# permissions for end users to edit cceendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cceendpoint-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eip-operator
    app.kubernetes.io/part-of: eip-operator
    app.kubernetes.io/managed-by: kustomize
  name: cceendpoint-editor-role
rules:
- apiGroups:
  - cce.baidubce.com
  resources:
  - cceendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cce.baidubce.com
  resources:
  - cceendpoints/status
  verbs:
  - get
