---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cce.baidubce.com
  resources:
  - cceendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cce.baidubce.com
  resources:
  - cceendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - cce.baidubce.com
  resources:
  - cceendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cce.baidubce.com
  resources:
  - eips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cce.baidubce.com
  resources:
  - eips/finalizers
  verbs:
  - update
- apiGroups:
  - cce.baidubce.com
  resources:
  - eips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cce.baidubce.com
  resources:
  - podeipbindstrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cce.baidubce.com
  resources:
  - podeipbindstrategies/finalizers
  verbs:
  - update
- apiGroups:
  - cce.baidubce.com
  resources:
  - podeipbindstrategies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
