[package]
name = "cni-xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.1", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
bindgen ={ version = "0.69.4", default-features = false, features = ["runtime"]}