// Code generated by go-swagger; DO NOT EDIT.

// /*
//  * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  * except in compliance with the License. You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software distributed under the
//  * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
//  * either express or implied. See the License for the specific language governing permissions
//  * and limitations under the License.
//  *
//  */

package endpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutEndpointProbeParams creates a new PutEndpointProbeParams object
// with the default values initialized.
func NewPutEndpointProbeParams() *PutEndpointProbeParams {
	var ()
	return &PutEndpointProbeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutEndpointProbeParamsWithTimeout creates a new PutEndpointProbeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutEndpointProbeParamsWithTimeout(timeout time.Duration) *PutEndpointProbeParams {
	var ()
	return &PutEndpointProbeParams{

		timeout: timeout,
	}
}

// NewPutEndpointProbeParamsWithContext creates a new PutEndpointProbeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutEndpointProbeParamsWithContext(ctx context.Context) *PutEndpointProbeParams {
	var ()
	return &PutEndpointProbeParams{

		Context: ctx,
	}
}

// NewPutEndpointProbeParamsWithHTTPClient creates a new PutEndpointProbeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutEndpointProbeParamsWithHTTPClient(client *http.Client) *PutEndpointProbeParams {
	var ()
	return &PutEndpointProbeParams{
		HTTPClient: client,
	}
}

/*
PutEndpointProbeParams contains all the parameters to send to the API endpoint
for the put endpoint probe operation typically these are written to a http.Request
*/
type PutEndpointProbeParams struct {

	/*CniDriver*/
	CniDriver *string
	/*ContainerID
	  container id provider by cni

	*/
	ContainerID *string
	/*Ifname
	  ifname provider by cni

	*/
	Ifname *string
	/*Netns
	  netns provider by cni

	*/
	Netns *string
	/*Owner*/
	Owner *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put endpoint probe params
func (o *PutEndpointProbeParams) WithTimeout(timeout time.Duration) *PutEndpointProbeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put endpoint probe params
func (o *PutEndpointProbeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put endpoint probe params
func (o *PutEndpointProbeParams) WithContext(ctx context.Context) *PutEndpointProbeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put endpoint probe params
func (o *PutEndpointProbeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put endpoint probe params
func (o *PutEndpointProbeParams) WithHTTPClient(client *http.Client) *PutEndpointProbeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put endpoint probe params
func (o *PutEndpointProbeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCniDriver adds the cniDriver to the put endpoint probe params
func (o *PutEndpointProbeParams) WithCniDriver(cniDriver *string) *PutEndpointProbeParams {
	o.SetCniDriver(cniDriver)
	return o
}

// SetCniDriver adds the cniDriver to the put endpoint probe params
func (o *PutEndpointProbeParams) SetCniDriver(cniDriver *string) {
	o.CniDriver = cniDriver
}

// WithContainerID adds the containerID to the put endpoint probe params
func (o *PutEndpointProbeParams) WithContainerID(containerID *string) *PutEndpointProbeParams {
	o.SetContainerID(containerID)
	return o
}

// SetContainerID adds the containerId to the put endpoint probe params
func (o *PutEndpointProbeParams) SetContainerID(containerID *string) {
	o.ContainerID = containerID
}

// WithIfname adds the ifname to the put endpoint probe params
func (o *PutEndpointProbeParams) WithIfname(ifname *string) *PutEndpointProbeParams {
	o.SetIfname(ifname)
	return o
}

// SetIfname adds the ifname to the put endpoint probe params
func (o *PutEndpointProbeParams) SetIfname(ifname *string) {
	o.Ifname = ifname
}

// WithNetns adds the netns to the put endpoint probe params
func (o *PutEndpointProbeParams) WithNetns(netns *string) *PutEndpointProbeParams {
	o.SetNetns(netns)
	return o
}

// SetNetns adds the netns to the put endpoint probe params
func (o *PutEndpointProbeParams) SetNetns(netns *string) {
	o.Netns = netns
}

// WithOwner adds the owner to the put endpoint probe params
func (o *PutEndpointProbeParams) WithOwner(owner *string) *PutEndpointProbeParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the put endpoint probe params
func (o *PutEndpointProbeParams) SetOwner(owner *string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *PutEndpointProbeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CniDriver != nil {

		// query param cni-driver
		var qrCniDriver string
		if o.CniDriver != nil {
			qrCniDriver = *o.CniDriver
		}
		qCniDriver := qrCniDriver
		if qCniDriver != "" {
			if err := r.SetQueryParam("cni-driver", qCniDriver); err != nil {
				return err
			}
		}

	}

	if o.ContainerID != nil {

		// query param containerID
		var qrContainerID string
		if o.ContainerID != nil {
			qrContainerID = *o.ContainerID
		}
		qContainerID := qrContainerID
		if qContainerID != "" {
			if err := r.SetQueryParam("containerID", qContainerID); err != nil {
				return err
			}
		}

	}

	if o.Ifname != nil {

		// query param ifname
		var qrIfname string
		if o.Ifname != nil {
			qrIfname = *o.Ifname
		}
		qIfname := qrIfname
		if qIfname != "" {
			if err := r.SetQueryParam("ifname", qIfname); err != nil {
				return err
			}
		}

	}

	if o.Netns != nil {

		// query param netns
		var qrNetns string
		if o.Netns != nil {
			qrNetns = *o.Netns
		}
		qNetns := qrNetns
		if qNetns != "" {
			if err := r.SetQueryParam("netns", qNetns); err != nil {
				return err
			}
		}

	}

	if o.Owner != nil {

		// query param owner
		var qrOwner string
		if o.Owner != nil {
			qrOwner = *o.Owner
		}
		qOwner := qrOwner
		if qOwner != "" {
			if err := r.SetQueryParam("owner", qOwner); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
