/*
 * Cce API
 *
 * CCE
 *
 * OpenAPI spec version: v1beta
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// EndpointStatusLog : Status log of endpoint

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct EndpointStatusLog {}

impl EndpointStatusLog {
    /// Status log of endpoint
    pub fn new() -> EndpointStatusLog {
        EndpointStatusLog {}
    }
}
