apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eip-leader-election-role
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eip-operator
    app.kubernetes.io/part-of: eip-operator
  {{- include "cce-network-eip-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eip-leader-election-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eip-operator
    app.kubernetes.io/part-of: eip-operator
  {{- include "cce-network-eip-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'eip-leader-election-role'
subjects:
- kind: ServiceAccount
  name: 'eip-operator'
  namespace: '{{ .Release.Namespace }}'