apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: eip-mutating-webhook-configuration
  labels:
  {{- include "cce-network-eip-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: 'eip-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-cce-baidubce-com-v2-cceendpoint
  failurePolicy: Fail
  name: mcceendpoint.kb.io
  rules:
  - apiGroups:
    - cce.baidubce.com
    apiVersions:
    - v2
    operations:
    - CREATE
    resources:
    - cceendpoints
  sideEffects: None