apiVersion: v1
kind: Service
metadata:
  name: eip-webhook-service
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: eip-operator
    app.kubernetes.io/part-of: eip-operator
  {{- include "cce-network-eip-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    control-plane: eip-operator
  {{- include "cce-network-eip-operator.selectorLabels" . | nindent 4 }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443