/*
 * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 *
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2 "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/apis/cce.baidubce.com/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetResourceSets implements NetResourceSetInterface
type FakeNetResourceSets struct {
	Fake *FakeCceV2
}

var netresourcesetsResource = schema.GroupVersionResource{Group: "cce.baidubce.com", Version: "v2", Resource: "netresourcesets"}

var netresourcesetsKind = schema.GroupVersionKind{Group: "cce.baidubce.com", Version: "v2", Kind: "NetResourceSet"}

// Get takes name of the netResourceSet, and returns the corresponding netResourceSet object, and an error if there is any.
func (c *FakeNetResourceSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.NetResourceSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(netresourcesetsResource, name), &v2.NetResourceSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.NetResourceSet), err
}

// List takes label and field selectors, and returns the list of NetResourceSets that match those selectors.
func (c *FakeNetResourceSets) List(ctx context.Context, opts v1.ListOptions) (result *v2.NetResourceSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(netresourcesetsResource, netresourcesetsKind, opts), &v2.NetResourceSetList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2.NetResourceSetList{ListMeta: obj.(*v2.NetResourceSetList).ListMeta}
	for _, item := range obj.(*v2.NetResourceSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested netResourceSets.
func (c *FakeNetResourceSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(netresourcesetsResource, opts))
}

// Create takes the representation of a netResourceSet and creates it.  Returns the server's representation of the netResourceSet, and an error, if there is any.
func (c *FakeNetResourceSets) Create(ctx context.Context, netResourceSet *v2.NetResourceSet, opts v1.CreateOptions) (result *v2.NetResourceSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(netresourcesetsResource, netResourceSet), &v2.NetResourceSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.NetResourceSet), err
}

// Update takes the representation of a netResourceSet and updates it. Returns the server's representation of the netResourceSet, and an error, if there is any.
func (c *FakeNetResourceSets) Update(ctx context.Context, netResourceSet *v2.NetResourceSet, opts v1.UpdateOptions) (result *v2.NetResourceSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(netresourcesetsResource, netResourceSet), &v2.NetResourceSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.NetResourceSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetResourceSets) UpdateStatus(ctx context.Context, netResourceSet *v2.NetResourceSet, opts v1.UpdateOptions) (*v2.NetResourceSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(netresourcesetsResource, "status", netResourceSet), &v2.NetResourceSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.NetResourceSet), err
}

// Delete takes name of the netResourceSet and deletes it. Returns an error if one occurs.
func (c *FakeNetResourceSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(netresourcesetsResource, name, opts), &v2.NetResourceSet{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetResourceSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(netresourcesetsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v2.NetResourceSetList{})
	return err
}

// Patch applies the patch and returns the patched netResourceSet.
func (c *FakeNetResourceSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.NetResourceSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(netresourcesetsResource, name, pt, data, subresources...), &v2.NetResourceSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.NetResourceSet), err
}
