/*
 * Copyright (c) 2023 Baidu, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 *
 */

// Code generated by lister-gen. DO NOT EDIT.

package v2

import (
	v2 "github.com/baidubce/baiducloud-cce-cni-driver/cce-network-v2/pkg/k8s/apis/cce.baidubce.com/v2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetResourceSetLister helps list NetResourceSets.
// All objects returned here must be treated as read-only.
type NetResourceSetLister interface {
	// List lists all NetResourceSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2.NetResourceSet, err error)
	// Get retrieves the NetResourceSet from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2.NetResourceSet, error)
	NetResourceSetListerExpansion
}

// netResourceSetLister implements the NetResourceSetLister interface.
type netResourceSetLister struct {
	indexer cache.Indexer
}

// NewNetResourceSetLister returns a new NetResourceSetLister.
func NewNetResourceSetLister(indexer cache.Indexer) NetResourceSetLister {
	return &netResourceSetLister{indexer: indexer}
}

// List lists all NetResourceSets in the indexer.
func (s *netResourceSetLister) List(selector labels.Selector) (ret []*v2.NetResourceSet, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2.NetResourceSet))
	})
	return ret, err
}

// Get retrieves the NetResourceSet from the index for a given name.
func (s *netResourceSetLister) Get(name string) (*v2.NetResourceSet, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2.Resource("netresourceset"), name)
	}
	return obj.(*v2.NetResourceSet), nil
}
